"""drop unused daily slap and rose count tables

`slap_count_today` and `rose_count_today` were added in 5bb8eb56aae8 for a
per-politician, per-day tally that was never wired up: both tables have sat
empty since, and nothing reads or writes them.

The daily counters the app actually serves live as `slap_count_today` /
`rose_count_today` **columns** on `chief_ministers` and `ministers` — that is
what `/most-slapped`, `/most-roasted`, `/most-judged` read and what
`app/tasks/daily_reset.py` zeroes at midnight. Those columns are untouched
here; only the two same-named standalone tables go.

Written by hand rather than autogenerated: dropping the model from
`app/db/model/` also drops these tables out of `target_metadata`, and
`env.py`'s `include_name` filter then hides them from autogenerate entirely.

The downgrade recreates them exactly as 5bb8eb56aae8 left them.

Revision ID: 4903dd144a43
Revises: c4996d43886d
Create Date: 2026-08-15 03:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4903dd144a43'
down_revision: Union[str, Sequence[str], None] = 'c4996d43886d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TYPE_CHECK = "politician_type in ('cm', 'union_minister', 'mp')"


def upgrade() -> None:
    """Drop the two unused tables."""
    op.drop_index(op.f('ix_slap_count_today_date'), table_name='slap_count_today')
    op.drop_table('slap_count_today')
    op.drop_index(op.f('ix_rose_count_today_date'), table_name='rose_count_today')
    op.drop_table('rose_count_today')


def downgrade() -> None:
    """Recreate them as 5bb8eb56aae8 defined them."""
    for side in ('rose', 'slap'):
        op.create_table(
            f'{side}_count_today',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('politician_type', sa.String(), nullable=False),
            sa.Column('politician_id', sa.Integer(), nullable=False),
            sa.Column('date', sa.Date(), nullable=False),
            sa.Column('count', sa.Integer(), server_default='0', nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.CheckConstraint(_TYPE_CHECK, name=f'ck_{side}_count_today_type'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint(
                'politician_type', 'politician_id', 'date',
                name=f'uq_{side}_count_today_day',
            ),
        )
        op.create_index(
            op.f(f'ix_{side}_count_today_date'), f'{side}_count_today',
            ['date'], unique=False,
        )
