"""mp performance tables

Revision ID: c4996d43886d
Revises: b41f7c0d92a5
Create Date: 2026-08-14 23:39:27.176315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4996d43886d'
down_revision: Union[str, Sequence[str], None] = 'b41f7c0d92a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mp_mplads_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('house', sa.Text(), nullable=True),
    sa.Column('tenure', sa.Text(), nullable=True),
    sa.Column('period_label', sa.Text(), nullable=False),
    sa.Column('financial_year', sa.Text(), nullable=True),
    sa.Column('period_start_date', sa.Date(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('funds_released', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('funds_sanctioned', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('funds_utilised', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('recommended_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('calamity_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('unspent_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('utilisation_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('works_recommended_count', sa.Integer(), nullable=True),
    sa.Column('works_sanctioned_count', sa.Integer(), nullable=True),
    sa.Column('works_completed_count', sa.Integer(), nullable=True),
    sa.Column('derived_fields', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp_id', 'house', 'tenure', 'period_label', name='uq_mp_mplads_funds_period')
    )
    op.create_index(op.f('ix_mp_mplads_funds_mp_id'), 'mp_mplads_funds', ['mp_id'], unique=False)
    op.create_index(op.f('ix_mp_mplads_funds_source_id'), 'mp_mplads_funds', ['source_id'], unique=False)
    op.create_table('mp_mplads_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('source_work_id', sa.Text(), nullable=False),
    sa.Column('external_work_id', sa.Text(), nullable=True),
    sa.Column('letter_no', sa.Text(), nullable=True),
    sa.Column('work_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('sub_sector', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('constituency', sa.Text(), nullable=True),
    sa.Column('constituency_id', sa.Integer(), nullable=True),
    sa.Column('implementing_agency', sa.Text(), nullable=True),
    sa.Column('vendor_name', sa.Text(), nullable=True),
    sa.Column('recommended_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sanctioned_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expenditure_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('remaining_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('work_status', sa.Text(), nullable=True),
    sa.Column('status_group', sa.Text(), nullable=True),
    sa.Column('recommended_date', sa.Date(), nullable=True),
    sa.Column('sanction_date', sa.Date(), nullable=True),
    sa.Column('work_start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('financial_year', sa.Text(), nullable=True),
    sa.Column('tenure', sa.Text(), nullable=True),
    sa.Column('house', sa.Text(), nullable=True),
    sa.Column('payment_count', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_work_id', name='uq_mp_mplads_works_source_work_id')
    )
    op.create_index(op.f('ix_mp_mplads_works_mp_id'), 'mp_mplads_works', ['mp_id'], unique=False)
    op.create_index('ix_mp_mplads_works_mp_recommended_date', 'mp_mplads_works', ['mp_id', 'recommended_date'], unique=False)
    op.create_index('ix_mp_mplads_works_mp_status', 'mp_mplads_works', ['mp_id', 'status_group'], unique=False)
    op.create_index(op.f('ix_mp_mplads_works_source_id'), 'mp_mplads_works', ['source_id'], unique=False)
    op.create_index(op.f('ix_mp_mplads_works_status_group'), 'mp_mplads_works', ['status_group'], unique=False)
    op.create_table('mp_parliamentary_committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('house', sa.Text(), nullable=True),
    sa.Column('term', sa.Text(), nullable=True),
    sa.Column('committee_name', sa.Text(), nullable=False),
    sa.Column('committee_type', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp_id', 'term', 'committee_name', name='uq_mp_parliamentary_committees_committee')
    )
    op.create_index(op.f('ix_mp_parliamentary_committees_mp_id'), 'mp_parliamentary_committees', ['mp_id'], unique=False)
    op.create_index(op.f('ix_mp_parliamentary_committees_source_id'), 'mp_parliamentary_committees', ['source_id'], unique=False)
    op.create_table('mp_parliamentary_debates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('house', sa.Text(), nullable=True),
    sa.Column('term', sa.Text(), nullable=True),
    sa.Column('session_name', sa.Text(), nullable=True),
    sa.Column('debate_date', sa.Date(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('debate_type', sa.Text(), nullable=True),
    sa.Column('is_bill', sa.Boolean(), nullable=True),
    sa.Column('is_private_member_bill', sa.Boolean(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp_id', 'content_hash', name='uq_mp_parliamentary_debates_content')
    )
    op.create_index(op.f('ix_mp_parliamentary_debates_debate_type'), 'mp_parliamentary_debates', ['debate_type'], unique=False)
    op.create_index('ix_mp_parliamentary_debates_mp_date', 'mp_parliamentary_debates', ['mp_id', 'debate_date'], unique=False)
    op.create_index(op.f('ix_mp_parliamentary_debates_mp_id'), 'mp_parliamentary_debates', ['mp_id'], unique=False)
    op.create_index(op.f('ix_mp_parliamentary_debates_source_id'), 'mp_parliamentary_debates', ['source_id'], unique=False)
    op.create_table('mp_parliamentary_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('house', sa.Text(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('period_start_date', sa.Date(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('attendance_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('debates_count', sa.Integer(), nullable=True),
    sa.Column('questions_count', sa.Integer(), nullable=True),
    sa.Column('starred_questions_count', sa.Integer(), nullable=True),
    sa.Column('unstarred_questions_count', sa.Integer(), nullable=True),
    sa.Column('private_member_bills_count', sa.Integer(), nullable=True),
    sa.Column('bills_participated_count', sa.Integer(), nullable=True),
    sa.Column('committees_count', sa.Integer(), nullable=True),
    sa.Column('issues_raised_count', sa.Integer(), nullable=True),
    sa.Column('derived_fields', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp_id', 'house', 'term', name='uq_mp_parliamentary_performance_term')
    )
    op.create_index(op.f('ix_mp_parliamentary_performance_mp_id'), 'mp_parliamentary_performance', ['mp_id'], unique=False)
    op.create_index(op.f('ix_mp_parliamentary_performance_source_id'), 'mp_parliamentary_performance', ['source_id'], unique=False)
    op.create_table('mp_parliamentary_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('house', sa.Text(), nullable=True),
    sa.Column('term', sa.Text(), nullable=True),
    sa.Column('session_name', sa.Text(), nullable=True),
    sa.Column('asked_on', sa.Date(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Text(), nullable=True),
    sa.Column('ministry', sa.Text(), nullable=True),
    sa.Column('subject_category', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp_id', 'content_hash', name='uq_mp_parliamentary_questions_content')
    )
    op.create_index('ix_mp_parliamentary_questions_mp_date', 'mp_parliamentary_questions', ['mp_id', 'asked_on'], unique=False)
    op.create_index(op.f('ix_mp_parliamentary_questions_mp_id'), 'mp_parliamentary_questions', ['mp_id'], unique=False)
    op.create_index(op.f('ix_mp_parliamentary_questions_question_type'), 'mp_parliamentary_questions', ['question_type'], unique=False)
    op.create_index(op.f('ix_mp_parliamentary_questions_source_id'), 'mp_parliamentary_questions', ['source_id'], unique=False)
    op.create_table('mp_parliamentary_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('house', sa.Text(), nullable=True),
    sa.Column('term', sa.Text(), nullable=True),
    sa.Column('session_name', sa.Text(), nullable=False),
    sa.Column('session_order', sa.Integer(), nullable=True),
    sa.Column('session_start_date', sa.Date(), nullable=True),
    sa.Column('session_end_date', sa.Date(), nullable=True),
    sa.Column('attendance_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sittings_attended', sa.Integer(), nullable=True),
    sa.Column('sittings_total', sa.Integer(), nullable=True),
    sa.Column('questions_count', sa.Integer(), nullable=True),
    sa.Column('debates_count', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp_id', 'term', 'session_name', name='uq_mp_parliamentary_sessions_session')
    )
    op.create_index(op.f('ix_mp_parliamentary_sessions_mp_id'), 'mp_parliamentary_sessions', ['mp_id'], unique=False)
    op.create_index(op.f('ix_mp_parliamentary_sessions_source_id'), 'mp_parliamentary_sessions', ['source_id'], unique=False)
    op.create_table('mp_performance_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('scope_value', sa.Text(), nullable=False),
    sa.Column('house', sa.Text(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('period_start_date', sa.Date(), nullable=True),
    sa.Column('period_end_date', sa.Date(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric', 'scope', 'scope_value', 'house', 'term', name='uq_mp_performance_benchmarks_metric')
    )
    op.create_index(op.f('ix_mp_performance_benchmarks_source_id'), 'mp_performance_benchmarks', ['source_id'], unique=False)
    op.create_table('mp_performance_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=True),
    sa.Column('homepage_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key', name='uq_mp_performance_sources_key')
    )
    op.create_table('mp_promises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('promise_text', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('made_on', sa.Date(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('evidence_url', sa.Text(), nullable=True),
    sa.Column('verified_on', sa.Date(), nullable=True),
    sa.Column('verified_by', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp_id', 'content_hash', name='uq_mp_promises_content')
    )
    op.create_index(op.f('ix_mp_promises_category'), 'mp_promises', ['category'], unique=False)
    op.create_index(op.f('ix_mp_promises_mp_id'), 'mp_promises', ['mp_id'], unique=False)
    op.create_index(op.f('ix_mp_promises_source_id'), 'mp_promises', ['source_id'], unique=False)

    # Declared here rather than on the models, following this repo's
    # convention: `mps` is reflected at runtime, so SQLAlchemy has no table
    # object to resolve the reference against at import time, and
    # `alembic/env.py` excludes foreign keys from autogenerate comparison
    # entirely so these are maintained by hand.

    op.create_foreign_key(
        'fk_mp_mplads_funds_mp', 'mp_mplads_funds', 'mps', ['mp_id'], ['id'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_mp_mplads_works_mp', 'mp_mplads_works', 'mps', ['mp_id'], ['id'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_mp_parliamentary_performance_mp', 'mp_parliamentary_performance', 'mps', ['mp_id'], ['id'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_mp_parliamentary_sessions_mp', 'mp_parliamentary_sessions', 'mps', ['mp_id'], ['id'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_mp_parliamentary_questions_mp', 'mp_parliamentary_questions', 'mps', ['mp_id'], ['id'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_mp_parliamentary_debates_mp', 'mp_parliamentary_debates', 'mps', ['mp_id'], ['id'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_mp_parliamentary_committees_mp', 'mp_parliamentary_committees', 'mps', ['mp_id'], ['id'], ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_mp_promises_mp', 'mp_promises', 'mps', ['mp_id'], ['id'], ondelete='CASCADE'
    )

    # Losing a source registry row must not delete the facts it described —
    # the per-row `source_url` still carries the attribution.
    op.create_foreign_key(
        'fk_mp_mplads_funds_source', 'mp_mplads_funds', 'mp_performance_sources',
        ['source_id'], ['id'], ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_mp_mplads_works_source', 'mp_mplads_works', 'mp_performance_sources',
        ['source_id'], ['id'], ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_mp_parliamentary_performance_source', 'mp_parliamentary_performance', 'mp_performance_sources',
        ['source_id'], ['id'], ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_mp_parliamentary_sessions_source', 'mp_parliamentary_sessions', 'mp_performance_sources',
        ['source_id'], ['id'], ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_mp_parliamentary_questions_source', 'mp_parliamentary_questions', 'mp_performance_sources',
        ['source_id'], ['id'], ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_mp_parliamentary_debates_source', 'mp_parliamentary_debates', 'mp_performance_sources',
        ['source_id'], ['id'], ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_mp_parliamentary_committees_source', 'mp_parliamentary_committees', 'mp_performance_sources',
        ['source_id'], ['id'], ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_mp_promises_source', 'mp_promises', 'mp_performance_sources',
        ['source_id'], ['id'], ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_mp_performance_benchmarks_source', 'mp_performance_benchmarks', 'mp_performance_sources',
        ['source_id'], ['id'], ondelete='SET NULL'
    )

    # Whether a politician kept a promise is the one claim in this feature that
    # must never be inferred, so the schema refuses to store a verdict without
    # a link to the evidence for it. 'unverified' is the only status a row may
    # carry on its own.
    op.create_check_constraint(
        'ck_mp_promises_status',
        'mp_promises',
        "status in ('completed', 'in_progress', 'not_started', 'unverified')",
    )
    op.create_check_constraint(
        'ck_mp_promises_status_needs_evidence',
        'mp_promises',
        "status = 'unverified' or evidence_url is not null",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_mp_promises_status_needs_evidence', 'mp_promises', type_='check')
    op.drop_constraint('ck_mp_promises_status', 'mp_promises', type_='check')
    op.drop_constraint('fk_mp_mplads_funds_source', 'mp_mplads_funds', type_='foreignkey')
    op.drop_constraint('fk_mp_mplads_works_source', 'mp_mplads_works', type_='foreignkey')
    op.drop_constraint('fk_mp_parliamentary_performance_source', 'mp_parliamentary_performance', type_='foreignkey')
    op.drop_constraint('fk_mp_parliamentary_sessions_source', 'mp_parliamentary_sessions', type_='foreignkey')
    op.drop_constraint('fk_mp_parliamentary_questions_source', 'mp_parliamentary_questions', type_='foreignkey')
    op.drop_constraint('fk_mp_parliamentary_debates_source', 'mp_parliamentary_debates', type_='foreignkey')
    op.drop_constraint('fk_mp_parliamentary_committees_source', 'mp_parliamentary_committees', type_='foreignkey')
    op.drop_constraint('fk_mp_promises_source', 'mp_promises', type_='foreignkey')
    op.drop_constraint('fk_mp_performance_benchmarks_source', 'mp_performance_benchmarks', type_='foreignkey')
    op.drop_constraint('fk_mp_mplads_funds_mp', 'mp_mplads_funds', type_='foreignkey')
    op.drop_constraint('fk_mp_mplads_works_mp', 'mp_mplads_works', type_='foreignkey')
    op.drop_constraint('fk_mp_parliamentary_performance_mp', 'mp_parliamentary_performance', type_='foreignkey')
    op.drop_constraint('fk_mp_parliamentary_sessions_mp', 'mp_parliamentary_sessions', type_='foreignkey')
    op.drop_constraint('fk_mp_parliamentary_questions_mp', 'mp_parliamentary_questions', type_='foreignkey')
    op.drop_constraint('fk_mp_parliamentary_debates_mp', 'mp_parliamentary_debates', type_='foreignkey')
    op.drop_constraint('fk_mp_parliamentary_committees_mp', 'mp_parliamentary_committees', type_='foreignkey')
    op.drop_constraint('fk_mp_promises_mp', 'mp_promises', type_='foreignkey')
    op.drop_index(op.f('ix_mp_promises_source_id'), table_name='mp_promises')
    op.drop_index(op.f('ix_mp_promises_mp_id'), table_name='mp_promises')
    op.drop_index(op.f('ix_mp_promises_category'), table_name='mp_promises')
    op.drop_table('mp_promises')
    op.drop_table('mp_performance_sources')
    op.drop_index(op.f('ix_mp_performance_benchmarks_source_id'), table_name='mp_performance_benchmarks')
    op.drop_table('mp_performance_benchmarks')
    op.drop_index(op.f('ix_mp_parliamentary_sessions_source_id'), table_name='mp_parliamentary_sessions')
    op.drop_index(op.f('ix_mp_parliamentary_sessions_mp_id'), table_name='mp_parliamentary_sessions')
    op.drop_table('mp_parliamentary_sessions')
    op.drop_index(op.f('ix_mp_parliamentary_questions_source_id'), table_name='mp_parliamentary_questions')
    op.drop_index(op.f('ix_mp_parliamentary_questions_question_type'), table_name='mp_parliamentary_questions')
    op.drop_index(op.f('ix_mp_parliamentary_questions_mp_id'), table_name='mp_parliamentary_questions')
    op.drop_index('ix_mp_parliamentary_questions_mp_date', table_name='mp_parliamentary_questions')
    op.drop_table('mp_parliamentary_questions')
    op.drop_index(op.f('ix_mp_parliamentary_performance_source_id'), table_name='mp_parliamentary_performance')
    op.drop_index(op.f('ix_mp_parliamentary_performance_mp_id'), table_name='mp_parliamentary_performance')
    op.drop_table('mp_parliamentary_performance')
    op.drop_index(op.f('ix_mp_parliamentary_debates_source_id'), table_name='mp_parliamentary_debates')
    op.drop_index(op.f('ix_mp_parliamentary_debates_mp_id'), table_name='mp_parliamentary_debates')
    op.drop_index('ix_mp_parliamentary_debates_mp_date', table_name='mp_parliamentary_debates')
    op.drop_index(op.f('ix_mp_parliamentary_debates_debate_type'), table_name='mp_parliamentary_debates')
    op.drop_table('mp_parliamentary_debates')
    op.drop_index(op.f('ix_mp_parliamentary_committees_source_id'), table_name='mp_parliamentary_committees')
    op.drop_index(op.f('ix_mp_parliamentary_committees_mp_id'), table_name='mp_parliamentary_committees')
    op.drop_table('mp_parliamentary_committees')
    op.drop_index(op.f('ix_mp_mplads_works_status_group'), table_name='mp_mplads_works')
    op.drop_index(op.f('ix_mp_mplads_works_source_id'), table_name='mp_mplads_works')
    op.drop_index('ix_mp_mplads_works_mp_status', table_name='mp_mplads_works')
    op.drop_index('ix_mp_mplads_works_mp_recommended_date', table_name='mp_mplads_works')
    op.drop_index(op.f('ix_mp_mplads_works_mp_id'), table_name='mp_mplads_works')
    op.drop_table('mp_mplads_works')
    op.drop_index(op.f('ix_mp_mplads_funds_source_id'), table_name='mp_mplads_funds')
    op.drop_index(op.f('ix_mp_mplads_funds_mp_id'), table_name='mp_mplads_funds')
    op.drop_table('mp_mplads_funds')
    # ### end Alembic commands ###
