"""mp wealth declaration table

Revision ID: c86730c38848
Revises: 6e29aea7ab01
Create Date: 2026-08-09 02:33:12.299503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c86730c38848'
down_revision: Union[str, Sequence[str], None] = '6e29aea7ab01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mp_wealth_declaration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('election_year', sa.Integer(), nullable=True),
    sa.Column('election_name', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('myneta_dataset_slug', sa.Text(), nullable=True),
    sa.Column('myneta_candidate_id', sa.Text(), nullable=True),
    sa.Column('total_assets', sa.BigInteger(), nullable=True),
    sa.Column('total_liabilities', sa.BigInteger(), nullable=True),
    sa.Column('movable_assets', sa.BigInteger(), nullable=True),
    sa.Column('immovable_assets', sa.BigInteger(), nullable=True),
    sa.Column('cash', sa.BigInteger(), nullable=True),
    sa.Column('bank_deposits', sa.BigInteger(), nullable=True),
    sa.Column('shares_investments', sa.BigInteger(), nullable=True),
    sa.Column('mutual_funds', sa.BigInteger(), nullable=True),
    sa.Column('jewellery', sa.BigInteger(), nullable=True),
    sa.Column('vehicles', sa.BigInteger(), nullable=True),
    sa.Column('residential_property', sa.BigInteger(), nullable=True),
    sa.Column('commercial_property', sa.BigInteger(), nullable=True),
    sa.Column('agricultural_land', sa.BigInteger(), nullable=True),
    sa.Column('other_assets', sa.BigInteger(), nullable=True),
    sa.Column('warnings', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp_id', name='uq_mp_wealth_declaration_mp')
    )
    op.create_index(op.f('ix_mp_wealth_declaration_mp_id'), 'mp_wealth_declaration', ['mp_id'], unique=False)
    # Declared here rather than on the model: `mps` is reflected at runtime, so
    # SQLAlchemy has no table object to resolve against at import time.
    op.create_foreign_key(
        'fk_mp_wealth_declaration_mp', 'mp_wealth_declaration', 'mps',
        ['mp_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_mp_wealth_declaration_mp', 'mp_wealth_declaration', type_='foreignkey')
    op.drop_index(op.f('ix_mp_wealth_declaration_mp_id'), table_name='mp_wealth_declaration')
    op.drop_table('mp_wealth_declaration')
    # ### end Alembic commands ###
